# Generated by Django 5.2.8 on 2025-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
    ]
