# Generated by Django 4.2.25 on 2025-11-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_credits_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_last_reset_idx',
        ),
    ]
