# Generated by Django 5.2.8 on 2025-12-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('curriculum', '0004_remove_legacyexammapping_curriculum_legacy_exam_subj_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='current_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_classes', to='curriculum.week'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_classes', to='curriculum.term'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherclass',
            unique_together={('teacher', 'school_level', 'subject', 'academic_session', 'term')},
        ),
    ]
