# Generated by Django 5.2.8 on 2025-12-17 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_add_term_to_teacher_class'),
        ('courses', '0005_alter_course_unique_together_course_curriculum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=20)),
                ('questions_data', models.JSONField(default=list, help_text='AI-generated exam questions')),
                ('user_answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_exams',
                'ordering': ['-created_at'],
            },
        ),
    ]
