# Generated by Django 5.2.8 on 2025-11-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JAMBSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, unique=True)),
                ('syllabus_content', models.TextField(help_text='Markdown format with LaTeX for formulas')),
                ('version', models.CharField(default='2025', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JAMB Syllabus',
                'verbose_name_plural': 'JAMB Syllabuses',
                'db_table': 'jamb_syllabus',
            },
        ),
        migrations.CreateModel(
            name='JSSSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, unique=True)),
                ('syllabus_content', models.TextField(help_text='Markdown format with LaTeX for formulas')),
                ('version', models.CharField(default='2025', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JSS Syllabus',
                'verbose_name_plural': 'JSS Syllabuses',
                'db_table': 'jss_syllabus',
            },
        ),
        migrations.CreateModel(
            name='SSCESyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, unique=True)),
                ('syllabus_content', models.TextField(help_text='Markdown format with LaTeX for formulas')),
                ('version', models.CharField(default='2025', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSCE Syllabus',
                'verbose_name_plural': 'SSCE Syllabuses',
                'db_table': 'ssce_syllabus',
            },
        ),
    ]
