# Generated by Django 4.2.25 on 2025-11-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exam',
            name='exams_user_course_idx',
        ),
        migrations.RemoveIndex(
            model_name='examquestion',
            name='exams_question_exam_idx',
        ),
    ]
