# Generated by Django 4.2.25 on 2025-11-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cachedlesson',
            name='courses_lesson_topic_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='module',
            name='courses_module_order_idx',
        ),
    ]
