# Generated by Django 5.2.8 on 2025-11-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_cachedlesson_cache_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='lesson_content',
        ),
        migrations.DeleteModel(
            name='CachedLesson',
        ),
    ]
