# Generated by Django 5.2.8 on 2025-12-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_cachedlesson_courses_lesson_topic_idx_and_more'),
        ('curriculum', '0004_remove_legacyexammapping_curriculum_legacy_exam_subj_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, help_text='Link to structured curriculum', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='curriculum.subjectcurriculum'),
        ),
        migrations.AddField(
            model_name='course',
            name='school_level',
            field=models.ForeignKey(blank=True, help_text='New class-level field (JS1-SS3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='curriculum.schoollevel'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term (First/Second/Third)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='curriculum.term'),
        ),
        migrations.AddField(
            model_name='module',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Link to curriculum topic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='curriculum.topic'),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('JAMB', 'JAMB'), ('SSCE', 'SSCE'), ('JSS', 'JSS')], help_text='Legacy field for backwards compatibility', max_length=10, null=True),
        ),
    ]
