# Generated by Django 5.2.8 on 2025-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name_plural': 'Quiz Attempts'},
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
