# Generated by Django 4.2.25 on 2025-11-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quizzes_user_module_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quizzes_user_passed_idx',
        ),
    ]
