# Generated by Django 5.2.8 on 2025-11-09 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('JAMB', 'JAMB'), ('SSCE', 'SSCE'), ('JSS', 'JSS')], max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('question_count', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('questions_data', models.JSONField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mock_exams',
            },
        ),
    ]
