# Generated by Django 5.2.8 on 2025-12-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='legacyexammapping',
            name='curriculum_legacy_exam_subj_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprogramme',
            name='curriculum_prog_user_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectcurriculum',
            name='curriculum_level_subj_term_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectenrolment',
            name='curriculum_enrol_prog_subj_idx',
        ),
        migrations.RemoveIndex(
            model_name='topic',
            name='curriculum_topic_curr_week_idx',
        ),
    ]
